import Head from 'next/head'
import {useState, useEffect} from 'react'
import Navbar from '../components/Navbar'
import Usercomponent from '../components/Usercomponent'
import SectionComponent from '../components/SectionComponent'
import FooterComponent from '../components/FooterComponent'
// import Switch from '../components/Switch'


export default function Home() {
  const [matgroups, setmatgroups] = useState([])
    
  useEffect(() => {
    const fetchMatgroups = async () => {
      const response = await fetch("/api/mongodbexample");
      const json = await response.json();
      setmatgroups(json);
    };
    fetchMatgroups();
  }, []);
  
  return (
    <div className="bg-light-primary dark:bg-dark-primary h-screen">
      <Head>
        <title>JAL MM Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <Navbar />
      <h1 className="text-xl font-bold p-5 text-dark-primary dark:text-light-primary">
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>
      
      {/* <Switch /> */}
      <div className="flex justify-center bg-slate-100 dark:bg-dark-primary">
        <Usercomponent matgroups={matgroups} />
      </div>

      <section>
        <SectionComponent />
      </section>

      <footer>
        <FooterComponent />
      </footer>
        
    </div>
  );
}



