import Head from 'next/head'
import {useState, useEffect} from 'react'
// import Navbar from '../components/Navbar'
import HeaderComponent from '../components/HeaderComponent'
import Matgrouplist from '../components/Matgrouplist'
// import Herocomponent from '../components/Herocomponent'
import FeaturesComponent from '../components/FeaturesComponent'
import SectionComponent from '../components/SectionComponent'
import FooterComponent from '../components/FooterComponent'
// import Switch from '../components/Switch'

// import { Link, animateScroll as scroll } from "react-scroll";


export default function Home() {
  const [matgroups, setmatgroups] = useState([]);

  useEffect(() => {
    const fetchMatgroups = async () => {
      const response = await fetch("/api/matgroup");
      const json = await response.json();
      setmatgroups(json);
    };
    fetchMatgroups();
  }, []);

  // Sticky Menu Area
  useEffect(() => {
    window.addEventListener("scroll", isSticky);
    return () => {
      window.removeEventListener("scroll", isSticky);
    };
  });

  /* Method that will fix header after a specific scrollable */
  const isSticky = (e) => {
    const header = document.querySelector("#sticky");
    const scrollTop = window.scrollY;
    scrollTop >= 100
      ? header.classList.add("is-sticky")
      : header.classList.remove("is-sticky");
  };

  return (
    <div className="bg-light-primary dark:bg-dark-primary h-screen">
      <Head>
        <title>JAL MM Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="sticky" ><HeaderComponent/></div>
      
      {/* <h1 className="text-xl font-bold p-5 text-dark-primary dark:text-light-primary">
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1> */}

      {/* <div >
        <Herocomponent />
      </div> */}

      <div>
        <FeaturesComponent id="features1" />
      </div>

      {/* <Switch /> */}
      <div className="flex justify-center bg-slate-100 dark:bg-dark-primary">
        <Matgrouplist matgroups={matgroups} id="user1"/>
      </div>

      <section>
        <SectionComponent id="section1" />
      </section>

      <footer>
        <FooterComponent id="footer1" />
      </footer>
    </div>
  );
}



